// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA252wSxXY8nZ-qooDy78_r2l7ndhAC_4s',
    appId: '1:1080221686184:web:2429bbfe10784c9c34e59d',
    messagingSenderId: '1080221686184',
    projectId: 'todoapp-3f528',
    authDomain: 'todoapp-3f528.firebaseapp.com',
    storageBucket: 'todoapp-3f528.appspot.com',
    measurementId: 'G-292SJVLFHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdvDcqektNphlMYdydGpNa-Re_S4ybhys',
    appId: '1:1080221686184:android:d32fde814ebe84a734e59d',
    messagingSenderId: '1080221686184',
    projectId: 'todoapp-3f528',
    storageBucket: 'todoapp-3f528.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtzel1OiVxf0cMaauWffG2YHdQxO7-3AI',
    appId: '1:1080221686184:ios:12f2aa1a9dd048b834e59d',
    messagingSenderId: '1080221686184',
    projectId: 'todoapp-3f528',
    storageBucket: 'todoapp-3f528.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtzel1OiVxf0cMaauWffG2YHdQxO7-3AI',
    appId: '1:1080221686184:ios:8ff04b55ba8020ff34e59d',
    messagingSenderId: '1080221686184',
    projectId: 'todoapp-3f528',
    storageBucket: 'todoapp-3f528.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
